name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]  # Versions dynamiques de Python
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install radon
        pip install networkx
    
    - name: Analysing the code with pylint
      id: pylint
      run: |
        pylint . --exit-zero > pylint-report.txt
        cat pylint-report.txt
        # Extraction du score en s'assurant que seule la ligne de score total est prise
        SCORE=$(grep -m 1 -oE 'Your code has been rated at [0-9]+(\.[0-9]+)?/10' pylint-report.txt | grep -oE '[0-9]+(\.[0-9]+)?' || echo "0")
        echo "Pylint score: $SCORE"
        echo "score=$SCORE" >> $GITHUB_ENV

    - name: Check Pylint Score
      run: |
        if (( $(echo "$SCORE < 8.0" | bc -l) )); then
          echo "Pylint score is below threshold"
          exit 1
        fi
      env:
        SCORE: ${{ env.score }}
